<a href="https://colab.research.google.com/github/Haseeb227/Pytorch/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
  print("Gpu is avaliable")
else:
  print("gpu not available")

gpu not available


# Creating a Tensor

In [5]:
# using empty
a = torch.empty(2,3)

In [7]:
#check type
type(a)

torch.Tensor

In [8]:
# using Zeros
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# usning ones
c = torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
d = torch.rand(2,3)
d

tensor([[0.7618, 0.4383, 0.1849],
        [0.4048, 0.3577, 0.5061]])

In [11]:
# using maunal seed
torch.manual_seed(2)
e = torch.rand(2,3)
e

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190]])

In [12]:
# using tensor
f = torch.tensor([[1,2,3],[5,6,7]])
f

tensor([[1, 2, 3],
        [5, 6, 7]])

In [14]:
# other ways

# other ways

# arange
print("using arange ->", torch.arange(0,10,2))
print()

# using linspace
print("using linspace ->", torch.linspace(0,10,10))
print()

# using eye
print("using eye ->", torch.eye(5))
print()

# using full
print("using full ->", torch.full((3, 3), 5))
print()

using arange -> tensor([0, 2, 4, 6, 8])

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])



# Tensor shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[             83,             113,       161453216],
        [134858226285888,               0,               0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.4425, 0.0958, 0.6142],
        [0.0573, 0.5657, 0.5332]])

## Mathematical operations

### 1. Scalar operation

In [24]:
x = torch.rand(2,2)
x

tensor([[0.7116, 0.2050],
        [0.3078, 0.9809]])

In [25]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5064, 0.0420],
        [0.0947, 0.9621]])

### 2. Element wise operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0103, 0.4660, 0.4604],
        [0.8547, 0.4525, 0.6317]])
tensor([[0.4760, 0.2200, 0.2166],
        [0.2571, 0.0458, 0.1755]])


In [27]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0103, 0.0260, 0.0272],
        [0.0834, 0.0403, 0.1051]])

In [28]:
c = torch.tensor([1, -2, 3, -4])

In [29]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [32]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [35]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[6., 1., 6.],
        [0., 9., 1.]])

In [37]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([13., 10.])

In [38]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.0000, 5.0000, 3.5000])

In [39]:
# median
torch.median(e)

tensor(1.)

In [40]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [41]:
# product
torch.prod(e)

tensor(0.)

In [42]:
# standard deviation
torch.std(e)

tensor(3.6560)

In [43]:
# variance
torch.var(e)

tensor(13.3667)

In [44]:
# argmax
torch.argmax(e)

tensor(4)

In [45]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [46]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 0, 8],
        [2, 8, 7]])
tensor([[1, 1],
        [1, 2],
        [0, 8]])


In [47]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 3, 67],
        [10, 74]])

In [48]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [49]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 2],
        [0, 8],
        [8, 7]])

In [50]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 2., 2.],
        [8., 8., 3.],
        [1., 1., 5.]])

In [51]:
# determinant
torch.det(h)

tensor(0.)

In [52]:
# inverse
torch.inverse(h)

_LinAlgError: linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

In [ ]:
# log
torch.log(k)

In [ ]:
# exp
torch.exp(k)

In [ ]:
# sqrt
torch.sqrt(k)

In [ ]:
# sigmoid
torch.sigmoid(k)

In [ ]:
# softmax
torch.softmax(k, dim=0)

In [ ]:
# relu
torch.relu(k)

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2018, 0.1089, 0.7653],
        [0.6473, 0.3401, 0.6406]])
tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])


In [ ]:
m.add_(n)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [ ]:
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m.relu_()

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838567488544

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838569581552